### ISSUE TITLE
bugs in GAMM_models.Rmd?

### ISSUE THREAD

**Issue by fvdslik** [PennLINC/Larsen_IronDevelopment#1]
Hi Bart,
running your GAMM_models.Rmd (excellent work BTW) results in several errors. I already included the 'dplyr' package but that does not solve the problem. The problem occurs in line 512:
    ### 2. Sequences with odd parameters
    dataTable <- dataTable %>%
    filter(sequence != 'B0map_v4_matchedFOV' & sequence != "B0map") %>% # Different voxel sizes
    filter(sequence != 'B0map_onesizefitsall_v3_T2S') %>% # small number of scans with odd params
    filter(!is.na(GOOD)&!is.na(Putamen)) # No r2* data available or no QC possible

It says: Error in group_keys.data.frame(data) :  LENGTH or similar applied to NULL object

The problem occurs several times in this chunk and in the ```{r cognition_sample} chunk. As a result, the summaryTable does not work. 

I am wondering if you could take a look to these issues? Thank you.

Best, Frans van der Slik

**Comment by bart-larsen** [comment]
Hello,

Thanks for pointing this out. It looks like the data.frame that is loaded is stored as a rowwise_df. You can fix the error by ungrouping the dataframe. For example, you can add this `ungroup()` to the following line:

```
dataTable <- dataTable %>%
  ungroup()%>%
  filter(bblid != 110689)%>%
  filter(!(ProjectName %in% c("DAY2_808799",
                              "FNDM1_810211",
                              "FNDM2_810211",
                              "NEFF_V2",
                              "NEFF_PILOT"
                              )
           )
         )
```

**Comment by bart-larsen** [comment]
I have also fixed this in the Rda file so you can either use the code above or pull again. Thanks for pointing this out!

**Comment by fvdslik** [comment]
Hi Bart,
sorry to be a pest. Running your GAMM_models.Rmd with the updated "brain_iron_data.Rda" results in an error in the chunk: "# ROI comparison
Analyses for figure 3". The command:
longTable$oldROI <- c("Caudate","Putamen","Accumbens_Area","Pallidum") does not function as expected. I ran into the following
Error:
! Assigned data `c("Caudate", "Putamen", "Accumbens_Area", "Pallidum")` must be compatible with existing data.
x Existing data has 4944 rows.
x Assigned data has 4 rows.
i Only vectors of size 1 are recycled.
Backtrace:
  1. base::`$<-`(`*tmp*`, oldROI, value = `<chr>`)
 12. tibble (local) `<fn>`(`<vctrs___>`)

I am wondering if you perhaps could solve this, too?

Best, Frans

**Comment by bart-larsen** [comment]
Hello,

No problem at all. That line is actually not needed and can be deleted. I pushed this change to the repo. Hopefully that works for you!
